### ISSUE TITLE
Json Format doesn't apply Locale Korean

### ISSUE THREAD

**Issue by thdefn** [ppp-team/my-petlog-server#71]
## 📌 Feature Issue
> Json Format doesn't apply Locale ko, so responses like "2024년 2월 8일 Thu요일"

<img width="432" alt="스크린샷 2024-02-15 오후 12 09 42" src="https://github.com/ppp-team/my-petlog-server/assets/80521474/9f182686-c995-45bc-aca9-114dc1cff35c">

## 📝 To-do
- [x] apply Locale Korean in Json Format

**Comment by llsrrll96** [comment]
이런 경우도 있군요
